# JEDI/configs/data_prep_config.yaml
#
# Configuration file for the 01_prepare_datasets.py script.
# Please edit according to your file paths and requirements.
# All paths are relative to the project root (JEDI/).

# Output directory for processed files.
output_dir: data/processed

# LLM name
#llm_name: vicuna_7b_v1_5
llm_name: Qwen2_5-7B-Instruct

# Jailbreak dataset configuration
jailbreak_dataset:
  # Input file path relative to the project root
  # input_file: data/raw/vicuna_7b_v1_5_sampled_jailbreaks.json
  input_file: data/raw/qwen_7b_chat_sampled_jailbreaks.json


# Benign dataset configuration (optional)
benign_dataset:
  sample_size: 100  # Number of samples to draw from the benign dataset
  input_files:
   # - data/raw/or-bench-80k.csv
    - data/raw/justeval.jsonl

# Prefix list used to generate A1 and A2 samples
prefixes:
  # Source file for prefixes. This makes the prefix list easier to manage and extend.
  # Source: https://github.com/IBM/activation-steering/blob/main/docs/demo-data/behavior_refusal.json
  source_file: data/raw/behavior_refusal.json

  # JSON key in 'source_file' for compliant (A1) prefixes
  compliance_key: "compliant_responses"

  # JSON key in 'source_file' for refusal (A2) prefixes
  refusal_key: "non_compliant_responses"
