# -*- coding: utf-8 -*-
"""Script 02: Extract model activation

This script follows the second stage in the "Methodflow.md" document and is responsible for extracting hidden states (activations) from the language model.
This version has been updated to support the double whitening process and to save disk space only saves aggregated activations.

Main functions:
1. Load the structured data set (A1-satisfied, A2-rejected, B1-benignly satisfied) generated by `01_prepare_datasets.py`.
2. Group data by 'prompt' to optimize performance.
3. For each batch, a complete conversation template is built from scratch and fed into the model.
4. Extract and save two types of activation windows for all sample types (A1, A2, B1):
    - "Early window" (early_window): corresponds to the hidden state of the prefix part.
    - "Content window" (content_window): corresponds to the hidden state of the newly generated content part.
5. **Modification**: For each window, only save a single vector aggregated according to the configuration (such as 'mean' or 'last').
    The original hidden state sequence token-by-token is no longer saved to significantly reduce storage usage.
6. Save the aggregated activation tensor directly in a dictionary (format: {layer: {window: tensor}}) and save the model's natural language output to a separate CSV file.
7. **Memory Optimization**: Adopt a block saving strategy, write data to temporary files and clear the memory every 10 batches processed.
    All temporary blocks are finally merged to handle large-scale data sets.

How to run:
python scripts/02_extract_activations.py --config configs/extraction_config.yaml"""
import argparse
import json
import logging
import torch
import yaml
import pandas as pd
from pathlib import Path
from tqdm import tqdm
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
import gc
from typing import List, Dict, Any

# Configure basic logging
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)


def is_qwen3_tokenizer(tokenizer) -> bool:
    """Return True when the loaded tokenizer belongs to the Qwen3 series."""
    tokenizer_name = str(getattr(tokenizer, "name_or_path", "")).lower()
    return "qwen3" in tokenizer_name


def apply_chat_template_compat(tokenizer, conversation, **kwargs):
    """Apply chat template with Qwen3-specific compatibility options."""
    if is_qwen3_tokenizer(tokenizer):
        kwargs["enable_thinking"] = False
    return tokenizer.apply_chat_template(conversation, **kwargs)


def find_subsequence(main_list: List[int], sub_list: List[int]) -> int:
    """Find the starting index of a sublist in the main list.

    Args:
        main_list (List[int]): Main token ID list.
        sub_list (List[int]): List of sub-token IDs to find.

    Returns:
        int: The starting index of the sublist in the main list, or -1 if not found."""
    main_len = len(main_list)
    sub_len = len(sub_list)
    for i in range(main_len - sub_len + 1):
        if main_list[i : i + sub_len] == sub_list:
            return i
    return -1


def get_model_and_tokenizer(model_name: str, model_kwargs: dict, device: str):
    """Load the specified Hugging Face model and tokenizer.

    Args:
        model_name (str): The name of the model to load from Hugging Face Hub.
        model_kwargs (dict): Keyword arguments for model loading (e.g., torch_dtype, load_in_8bit).
        device (str): The device to move the model to if not using 8-bit loading.

    Returns:
        tuple: A tuple containing the loaded model, tokenizer, and model configuration.
    """
    logging.info(f"Loading model '{model_name}'...")
    # Copy keyword arguments to avoid modifying the original configuration dictionary
    kwargs = model_kwargs.copy()

    # Safely evaluate torch_dtype strings, converting them from strings to torch.dtype objects
    if "torch_dtype" in kwargs and isinstance(kwargs["torch_dtype"], str):
        try:
            kwargs["torch_dtype"] = getattr(torch, kwargs["torch_dtype"])
        except AttributeError:
            # If "auto", remain "auto", handled automatically by transformers
            if kwargs["torch_dtype"] != "auto":
                raise ValueError(f"Invalid torch_dtype:{kwargs['torch_dtype']}")

                # Check if loaded in 8-bit mode
    load_in_8bit = kwargs.get("load_in_8bit", False)
    if load_in_8bit:
        logging.info("Loading model in 8-bit mode.")
        # 8-bit loading usually works best with device_map="auto"
        if "device_map" not in kwargs:
            kwargs["device_map"] = "auto"
            # Load model with 8-bit quantization
        model = AutoModelForCausalLM.from_pretrained(model_name, **kwargs)
    else:
        # Original logic for full precision loading
        model = AutoModelForCausalLM.from_pretrained(model_name, **kwargs).to(device)

    model.eval()  # Set the model to evaluation mode
    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=True,
        padding_side="left",  # Set to left padding to avoid warnings when generating
    )
    # If the tokenizer has no pad token, set it to eos token
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        # (Optional) Make sure the model configuration is in sync with the tokenizer
    model.config.pad_token_id = tokenizer.pad_token_id

    config = AutoConfig.from_pretrained(model_name, trust_remote_code=True)

    logging.info("The model and tokenizer are loaded successfully.")
    return model, tokenizer, config


def aggregate_activations(
    activations: torch.Tensor, method: str, max_tokens: int = 0
) -> torch.Tensor:
    """Aggregate hidden states along the sequence length dimension.

    Args:
        activations (torch.Tensor): Tensor of shape (batch_size, seq_len, hidden_dim).
        method (str): Aggregation method, 'mean' (average) or 'last' (take the last one).
        max_tokens (int, optional): If method is 'mean', only the first max_tokens tokens are used to calculate the average.
                                    The default is 0, which means all tokens are used.

    Returns:
        torch.Tensor: Aggregated tensor of shape (batch_size, hidden_dim)."""
    if method == "mean":
        # If max_tokens is specified and the current sequence length exceeds this value, truncate
        if max_tokens > 0 and activations.shape[1] > max_tokens:
            activations = activations[:, :max_tokens, :]
        return activations.mean(dim=1)
    elif method == "last":
        return activations[:, -1, :]
    else:
        raise ValueError(f"Unknown aggregation method:{method}")


def process_batch(
    batch_df, model, tokenizer, generation_config, extraction_config, device
):
    """Process a batch of data to extract activations.
    This release enhances memory management by removing temporary variables."""
    current_batch_size = len(batch_df)
    conversations = [json.loads(conv_str) for conv_str in batch_df["conversation"]]

    # --- Unified construction of input text ---
    full_input_texts = []
    for conv in conversations:
        text = apply_chat_template_compat(
            tokenizer,
            conv, tokenize=False, add_generation_prompt=False
        )
        if tokenizer.eos_token:
            text = text.rstrip()
            if text.endswith(tokenizer.eos_token):
                text = text[: -len(tokenizer.eos_token)]
        full_input_texts.append(text)

    inputs = tokenizer(
        full_input_texts, return_tensors="pt", padding=True, truncation=True
    ).to(device)
    del full_input_texts  # Delete a used list
    padded_prompt_len = inputs["input_ids"].shape[1]

    with torch.no_grad():
        # --- Step 1: Generate complete token sequence ---
        generated_sequences = model.generate(
            **inputs,
            max_new_tokens=generation_config["max_new_tokens"],
            pad_token_id=tokenizer.pad_token_id,
            do_sample=False,
        )
        # `inputs` is no longer needed after generate
        del inputs

        # --- Decoding and index lookup ---
        assistant_outputs = []
        prefix_start_indices = [-1] * current_batch_size

        for i in range(current_batch_size):
            prefix_text = conversations[i][1]["content"]
            prefix_ids = tokenizer.encode(prefix_text, add_special_tokens=False)
            prompt_ids_list = generated_sequences[i, :padded_prompt_len].tolist()
            start_idx = find_subsequence(prompt_ids_list, prefix_ids)
            if start_idx != -1:
                prefix_start_indices[i] = start_idx
                tokens_to_decode = generated_sequences[i, start_idx:]
                output_text = tokenizer.decode(
                    tokens_to_decode, skip_special_tokens=True
                )
                assistant_outputs.append(output_text)
            else:
                logging.warning(
                    f"Unable to sample{i}Positioning prefix token. Fallback to length-based decoding."
                )
                decoded_new_part = tokenizer.decode(
                    generated_sequences[i, padded_prompt_len:], skip_special_tokens=True
                )
                assistant_outputs.append(prefix_text + decoded_new_part)

        del prefix_ids, prompt_ids_list  # Delete temporary variables in loop

        # --- Step 2: Perform a forward pass on the complete sequence to obtain all hidden states ---
        full_outputs = model(generated_sequences, output_hidden_states=True)
        all_hidden_states = [h.cpu() for h in full_outputs.hidden_states]
        # `full_outputs` contains the computational graph and raw tensors and is the main memory consumer
        del full_outputs

        # --- MODIFICATION START: Initialize a simpler data structure ---
    batch_activations = {
        layer: {"early_window": [], "content_window": []}
        for layer in extraction_config["layers"]
    }
    # --- MODIFICATION END ---

    # Get the mean_k parameter from the configuration (if present), defaults to 0 (no truncation)
    mean_k = extraction_config.get("mean_k", 0)

    # --- Extract activation ---
    for layer_idx in extraction_config["layers"]:
        layer_hidden_states = all_hidden_states[layer_idx]

        # --- MODIFICATION START: Extract and store only aggregate activations of 'content_window' ---
        content_window_states = layer_hidden_states[:, padded_prompt_len:, :]
        if content_window_states.shape[1] > 0:
            # Key modification: Apply mean_k truncation only to content_window
            agg_content_batch = aggregate_activations(
                content_window_states,
                extraction_config["aggregation"],
                max_tokens=mean_k,
            )
            batch_activations[layer_idx]["content_window"].append(
                agg_content_batch.cpu()
            )
            del agg_content_batch
        del content_window_states
        # --- MODIFICATION END ---

        for i in range(current_batch_size):
            prefix_start_idx = prefix_start_indices[i]
            if prefix_start_idx == -1:
                continue

            prefix_text = conversations[i][1]["content"]
            prefix_ids = tokenizer.encode(prefix_text, add_special_tokens=False)
            prefix_len = len(prefix_ids)

            if prefix_len > 0:
                prefix_end_idx = prefix_start_idx + prefix_len
                early_window_slice = layer_hidden_states[
                    i, prefix_start_idx:prefix_end_idx, :
                ].unsqueeze(0)

                # --- MODIFICATION START: Extract and store only aggregate activations of 'early_window' ---
                # For early_window (prefix), we usually do not use k truncation, leaving max_tokens=0
                agg_early = aggregate_activations(
                    early_window_slice, extraction_config["aggregation"], max_tokens=0
                )
                batch_activations[layer_idx]["early_window"].append(agg_early.cpu())
                del early_window_slice, agg_early
                # --- MODIFICATION END ---

        del layer_hidden_states

        # Final cleanup before function returns
    del all_hidden_states
    del generated_sequences
    gc.collect()

    return batch_activations, assistant_outputs


def aggregate_and_format_chunk(activations_dict: Dict) -> Dict:
    """Aggregates and formats activation data within a chunk so that it can be saved."""
    chunk_tensors = {}
    for layer_idx, windows in activations_dict.items():
        chunk_tensors[layer_idx] = {}
        if windows["early_window"]:
            chunk_tensors[layer_idx]["early_window"] = torch.cat(
                windows["early_window"], dim=0
            )
        if windows["content_window"]:
            chunk_tensors[layer_idx]["content_window"] = torch.cat(
                windows["content_window"], dim=0
            )
    return chunk_tensors


def main():
    parser = argparse.ArgumentParser(
        description="Extract hidden state activations from language models based on profiles.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "--config",
        type=str,
        default="../configs/extraction_config.yaml",
        help="YAML configuration file path for the extraction phase. \\nDefault: ../configs/extraction_config.yaml",
    )
    args = parser.parse_args()

    # --- 1. Load configuration ---
    config_path = Path(args.config)
    if not config_path.is_file():
        logging.error(f"Configuration file not found:{config_path}")
        return
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

        # --- 2. Set path and load model ---
    base_dir = Path(__file__).parent.parent
    processed_data_dir = base_dir / config["processed_data_dir"]
    llm_name = config["dataset_llm_name"]
    output_dir = base_dir / config["output_dir"] / llm_name
    output_dir.mkdir(parents=True, exist_ok=True)
    logging.info(f"All activation and output files will be saved to:{output_dir}")
    dataset_llm_name = config["dataset_llm_name"]
    model, tokenizer, model_config_details = get_model_and_tokenizer(
        config["model_name"],
        config.get("model_kwargs", {}),
        config["processing"]["device"],
    )
    num_hidden_layers = getattr(model_config_details, "num_hidden_layers", float("inf"))
    requested_layers = config["extraction"]["layers"]
    valid_layers = [l for l in requested_layers if 0 <= l < num_hidden_layers]
    if not valid_layers:
        logging.error(
            f"requested layer{requested_layers}Invalid (number of model layers:{num_hidden_layers}). Aborting."
        )
        return
    config["extraction"]["layers"] = valid_layers
    logging.info(
        f"Activations will be extracted from the following layers:{valid_layers}"
    )
    sample_size = config.get("processing", {}).get("sample_size", 0)
    datasets_to_process = {
        "compliance": processed_data_dir
        / f"{dataset_llm_name}_jailbreak_compliance.csv",
        "refusal": processed_data_dir / f"{dataset_llm_name}_jailbreak_refusal.csv",
        "benign": processed_data_dir / f"{dataset_llm_name}_benign_compliance.csv",
    }

    # --- 3. Traverse and process each data set ---
    for name, path in datasets_to_process.items():
        if not path.is_file():
            logging.warning(
                f"not found '{name}'Dataset file, path:{path}, is skipping."
            )
            continue

        logging.info(f"---Dataset being processed:{name} ---")
        df = pd.read_csv(path)

        if sample_size > 0 and sample_size < len(df):
            logging.info(
                f"data set '{name}' Include{len(df)}samples. Randomly sampling based on configuration{sample_size}samples..."
            )
            df = df.sample(n=sample_size, random_state=42).reset_index(drop=True)

            # Define final and temporary file paths
        final_pt_path = output_dir / f"{llm_name}_{name}_activations.pt"
        final_csv_path = output_dir / f"{llm_name}_{name}_outputs.csv"

        # Clean up temporary files that may be left over from the previous run
        for temp_file in output_dir.glob(f"{llm_name}_{name}_activations_chunk_*.pt"):
            temp_file.unlink()
        if final_csv_path.exists():
            final_csv_path.unlink()

            # Initialize the container used to store the current block data

        def get_empty_activations_dict():
            return {
                layer: {"early_window": [], "content_window": []}
                for layer in config["extraction"]["layers"]
            }

        chunk_activations = get_empty_activations_dict()
        chunk_outputs_for_csv = []
        chunk_index = 0
        batches_in_chunk = 0

        batch_size = config["processing"]["batch_size"]
        use_grouping = "prompt" in df.columns
        grouped = df.groupby("prompt") if use_grouping else [("all", df)]
        progress_bar = tqdm(total=len(df), desc=f"Extracting{name}")

        # --- 4. Process by group and batch ---
        processed_rows = 0
        for prompt, group_df in grouped:
            for i in range(0, len(group_df), batch_size):
                batch_df = group_df.iloc[i : i + batch_size]
                batch_activations, assistant_outputs = process_batch(
                    batch_df,
                    model,
                    tokenizer,
                    config["generation"],
                    config["extraction"],
                    config["processing"]["device"],
                )

                # Accumulate the results of the current block
                for idx, assistant_text in enumerate(assistant_outputs):
                    original_row = batch_df.iloc[idx]
                    output_record = {
                        "prompt": original_row["prompt"],
                        "assistant_output": assistant_text,
                    }
                    for col in [
                        "prefix",
                        "behavior",
                        "FunctionalCategory",
                        "ContextString",
                        "source",
                    ]:
                        if col in original_row:
                            output_record[col] = original_row[col]
                    chunk_outputs_for_csv.append(output_record)

                for layer_idx, windows in batch_activations.items():
                    if windows["early_window"]:
                        chunk_activations[layer_idx]["early_window"].extend(
                            windows["early_window"]
                        )
                    if windows["content_window"]:
                        chunk_activations[layer_idx]["content_window"].extend(
                            windows["content_window"]
                        )

                del batch_activations, assistant_outputs
                batches_in_chunk += 1
                processed_rows += len(batch_df)
                progress_bar.update(len(batch_df))

                # --- 5. Check whether the block needs to be saved ---
                is_last_batch_of_dataset = processed_rows == len(df)
                if (
                    batches_in_chunk >= 20 or is_last_batch_of_dataset
                ) and chunk_outputs_for_csv:
                    logging.info(
                        f"Processed{batches_in_chunk}batches, saving blocks{chunk_index}..."
                    )

                    # Format and save activation block
                    chunk_tensors = aggregate_and_format_chunk(chunk_activations)
                    chunk_pt_path = (
                        output_dir
                        / f"{llm_name}_{name}_activations_chunk_{chunk_index}.pt"
                    )
                    torch.save(chunk_tensors, chunk_pt_path)

                    # Save output chunks to CSV
                    output_df = pd.DataFrame(chunk_outputs_for_csv)
                    if name == "benign":
                        cols_order = ["prompt", "prefix", "assistant_output", "source"]
                    else:
                        output_df["label"] = None
                        cols_order = [
                            "prompt",
                            "prefix",
                            "behavior",
                            "FunctionalCategory",
                            "ContextString",
                            "assistant_output",
                            "label",
                        ]
                    final_cols = [col for col in cols_order if col in output_df.columns]
                    output_df = output_df[final_cols]

                    # Only the first block needs to be written to the header
                    is_first_chunk = chunk_index == 0
                    output_df.to_csv(
                        final_csv_path,
                        mode="a",
                        index=False,
                        header=is_first_chunk,
                        encoding="utf-8-sig",
                    )

                    # Reset the container to free up memory
                    chunk_activations = get_empty_activations_dict()
                    chunk_outputs_for_csv = []
                    batches_in_chunk = 0
                    chunk_index += 1

                    del chunk_tensors, output_df
                    gc.collect()
                    if torch.cuda.is_available():
                        torch.cuda.empty_cache()
        progress_bar.close()

        # --- 6. Merge all activation blocks ---
        logging.info(
            f"Merging{chunk_index}activation blocks to create the final file..."
        )
        final_activations = get_empty_activations_dict()

        for i in range(chunk_index):
            chunk_path = output_dir / f"{llm_name}_{name}_activations_chunk_{i}.pt"
            if not chunk_path.exists():
                logging.warning(f"block file not found{chunk_path},jump over.")
                continue

            chunk_data = torch.load(chunk_path, map_location="cpu")
            for layer_idx, windows in chunk_data.items():
                if "early_window" in windows:
                    final_activations[layer_idx]["early_window"].append(
                        windows["early_window"]
                    )
                if "content_window" in windows:
                    final_activations[layer_idx]["content_window"].append(
                        windows["content_window"]
                    )

            del chunk_data
            chunk_path.unlink()  # Delete merged block files

            # Aggregate all blocks last time
        final_tensors_to_save = aggregate_and_format_chunk(final_activations)
        torch.save(final_tensors_to_save, final_pt_path)
        logging.info(
            f"Success will '{name}''s activations are merged and saved to{final_pt_path}"
        )

        # Clean memory
        del df, final_activations, final_tensors_to_save
        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    logging.info(
        "The activation extraction and output saving process for all datasets has been completed."
    )


if __name__ == "__main__":
    main()
