# -*- coding: utf-8 -*-
"""Script 03: Extract representation vectors and calculate Token scores

The script follows stages two and three in the "Methodflow.md" document and prepares data for stage four.

Main functions:
1. **Vector extraction**:
    - Load post-aggregation activations extracted by `02_extract_activations.py` (format: {layer: {window: tensor}}).
    - Load harmfulness labels generated by `02.5_judge_harmfulness.py`.
    - Filter samples to keep only harmful "compliance" (A1) and harmless "refusal" (A2) samples.
    - Calculate whitening/centering transformations separately for "Early Window" and "Content Window".
    - Extract intervention vector `v_l` (denial behavior) and condition vector `c_l` (harmful content).
    - (Optional) Decouple and visualize vectors.
    - Save the transformation matrix and extracted vectors.
2. **Score calculation (optimized version)**:
    - After vector extraction, load the underlying language model.
    - **Efficiently** reprocess all filtered samples (A1, A2, B1), utilizing the existing `assistant_output`.
    - Build `prompt` and `assistant_output` into complete conversations and perform a forward pass.
    - For each sample, obtain the hidden state of each token in its `assistant_output` part.
    - Compute the token-wise raw score `s_t` using the extracted condition vector `c_l` and the transformation.
    - Save token-by-token score sequences of all samples to .pt files by data set type for use by `04_calibrate_defense.py`.

How to run:
python scripts/03_extract_vectors.py --config configs/extract_vectors_config.yaml"""

import argparse
import yaml
import torch
import pandas as pd
import numpy as np
from pathlib import Path
import logging
from sklearn.decomposition import PCA
from tqdm import tqdm
import matplotlib.pyplot as plt
import seaborn as sns
import json
import gc
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
from typing import Dict, List

# Configuration log
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s"
)


def is_qwen3_tokenizer(tokenizer) -> bool:
    """Return True when the loaded tokenizer belongs to the Qwen3 series."""
    tokenizer_name = str(getattr(tokenizer, "name_or_path", "")).lower()
    return "qwen3" in tokenizer_name


def apply_chat_template_compat(tokenizer, conversation, **kwargs):
    """Apply chat template with Qwen3-specific compatibility options."""
    if is_qwen3_tokenizer(tokenizer):
        kwargs["enable_thinking"] = False
    return tokenizer.apply_chat_template(conversation, **kwargs)


def load_and_filter_data(
    data_dir: Path, llm_name: str, dataset_name: str
) -> tuple[dict, pd.DataFrame]:
    """Load activation tensors and corresponding labeled CSV files and filter based on labels.
    This version adapts the simplified activation data structure {layer: {window: tensor}}.
    """
    activations_path = data_dir / f"{llm_name}_{dataset_name}_activations.pt"
    outputs_path = data_dir / f"{llm_name}_{dataset_name}_outputs.csv"

    if not activations_path.exists() or not outputs_path.exists():
        logging.warning(
            f"not found{dataset_name}Activation or output file, skip loading. path:{activations_path}"
        )
        return None, None

    logging.info(f"Loading{dataset_name}data...")
    activations = torch.load(activations_path, map_location="cpu")
    df = pd.read_csv(outputs_path)

    if dataset_name == "benign":
        # For benign data, no filtering is required, and the loaded activation and df are returned directly.
        return activations, df

        # --- Filter compliance and refusal data ---
    if dataset_name == "compliance":
        target_label = "yes"
    elif dataset_name == "refusal":
        target_label = "no"
    else:
        # Unexpected situations, as a safety protection
        return activations, df

    initial_count = len(df)
    df.dropna(subset=["label"], inplace=True)
    valid_indices = df.index[df["label"] == target_label].tolist()

    df_filtered = df.loc[valid_indices].reset_index(drop=True)

    activations_filtered = {}
    for layer, windows in activations.items():
        activations_filtered[layer] = {}
        for window_name, tensor in windows.items():
            if tensor is None:
                continue

            if tensor.shape[0] != initial_count:
                logging.warning(
                    f"exist{dataset_name} (L{layer}, {window_name}), the number of activations ({tensor.shape[0]}) and the number of CSV rows ({initial_count}) does not match. Skip this tensor."
                )
                continue

            activations_filtered[layer][window_name] = tensor[valid_indices]

    logging.info(
        f"for{dataset_name},from{initial_count}filtered out from samples{len(df_filtered)}tagged '{target_label}' sample."
    )
    return activations_filtered, df_filtered


def calculate_dual_transforms(
    benign_activations: dict, whitening_config: dict
) -> tuple[dict, dict]:
    """Two sets of transformations for "behavioral" (early_window) and "semantic" (content_window) are computed based on benign activations.
    Transformations include mean (for centering) and optional whitening matrix."""
    whitening_enabled = whitening_config.get("enabled", True)
    epsilon = whitening_config.get("epsilon", 1e-4)

    if whitening_enabled:
        logging.info("Computing double whitening transform (early/content)...")
    else:
        logging.info("Whitening is disabled. Calculate the mean only for centering...")

    transforms_early = {}
    transforms_cont = {}

    for layer in tqdm(
        benign_activations.keys(), desc="Calculate transformation matrix"
    ):
        for window_name in ["early_window", "content_window"]:
            if (
                window_name in benign_activations[layer]
                and benign_activations[layer][window_name].shape[0] > 1
            ):
                H_benign = (
                    benign_activations[layer][window_name].to(torch.float32).cuda()
                )
                mu = H_benign.mean(dim=0)
                W = None
                W_inv = None

                if whitening_enabled:
                    H_centered = H_benign - mu
                    cov = (H_centered.T @ H_centered) / (H_centered.shape[0] - 1)
                    cov_reg = cov + torch.eye(cov.shape[0]).cuda() * epsilon
                    eigenvalues, eigenvectors = torch.linalg.eigh(cov_reg)

                    if (eigenvalues < 0).any():
                        logging.warning(
                            f"In the first{layer}layer ({window_name}) finds negative eigenvalues. Minimum eigenvalue:{eigenvalues.min().item()}"
                        )
                        eigenvalues = torch.clamp(eigenvalues, min=1e-6)

                    D_inv_sqrt = torch.diag(1.0 / torch.sqrt(eigenvalues))
                    W = D_inv_sqrt @ eigenvectors.T

                    D_sqrt = torch.diag(torch.sqrt(eigenvalues))
                    W_inv = eigenvectors @ D_sqrt

                transform_tuple = (
                    W.cpu() if W is not None else None,
                    mu.cpu(),
                    W_inv.cpu() if W_inv is not None else None,
                )
                if window_name == "early_window":
                    transforms_early[layer] = transform_tuple
                else:
                    transforms_cont[layer] = transform_tuple
            else:
                logging.warning(
                    f"No.{layer}Layer missing '{window_name}' for a benign activation, the transformation of this window cannot be calculated."
                )

    return transforms_early, transforms_cont


def apply_transform(activations: torch.Tensor, transform: tuple) -> torch.Tensor:
    """Applies a transformation (centering and optional whitening) to the given activation tensor.
    Supports 2D (N, D) or 3D (B, N, D) tensors."""
    W, mu, _ = transform
    # Make sure you are working on the same device
    device = activations.device
    mu_device = mu.to(device)

    centered = activations - mu_device

    if W is not None:
        W_device = W.to(device)
        # Use einsum to support 2D and 3D
        if activations.dim() == 2:
            transformed = torch.einsum("nd,cd->nc", centered, W_device)
        elif activations.dim() == 3:
            transformed = torch.einsum("bnd,cd->bnc", centered, W_device)
        else:
            raise ValueError(f"Unsupported activation dimensions:{activations.dim()}")
        return transformed
    else:  # Only centralization
        return centered


def get_diff_vector(
    pos_activations: torch.Tensor, neg_activations: torch.Tensor
) -> torch.Tensor:
    """Direction vectors are extracted by directly calculating the mean difference [normalization removed]."""
    mean_diff = pos_activations.mean(dim=0) - neg_activations.mean(dim=0)
    # Edit: Remove normalization
    norm = torch.norm(mean_diff)
    if norm == 0:
        logging.warning(
            "The norm of the mean difference vector is zero. Returns a zero vector."
        )
        return torch.zeros_like(mean_diff)
        # vector = mean_diff / norm # <-- removed
    return mean_diff  # <-- Directly returns the vector of the original modulo length


def plot_pca_visualizations(
    llm_name: str,
    window_name: str,
    layers: list,
    activations: dict,
    vectors: dict,
    output_dir: Path,
    whitening_enabled: bool,
    sample_size: int = 200,
):
    """Perform PCA dimensionality reduction on the activation of the specified window and generate a visual chart."""
    logging.info(f"Working on '{window_name}'Generate PCA visualization plot...")
    sns.set_theme(style="whitegrid", palette="deep")

    all_colors = {
        "Benign": "#2ca02c",
        "Refusal": "#1f77b4",
        "Compliance": "#d62728",
    }
    vec_colors = {"c_vector": "#9467bd", "v_vector": "#ff7f0e"}

    n_layers = len(layers)
    n_cols = 4
    n_rows = (n_layers + n_cols - 1) // n_cols
    fig, axes = plt.subplots(
        n_rows, n_cols, figsize=(n_cols * 5, n_rows * 5), squeeze=False
    )
    axes = axes.flatten()

    for i, layer in enumerate(tqdm(layers, desc=f"draw{window_name}")):
        ax = axes[i]

        z_compliance = activations[layer].get("compliance")
        z_refusal = activations[layer].get("refusal")
        z_benign = activations[layer].get("benign")

        data_to_plot = {}
        plot_colors = {}

        if window_name == "early_window":
            if z_compliance is not None and len(z_compliance) > 0:
                data_to_plot["Compliance"] = z_compliance
            if z_refusal is not None and len(z_refusal) > 0:
                data_to_plot["Refusal"] = z_refusal
        elif window_name == "content_window":
            if z_compliance is not None and len(z_compliance) > 0:
                data_to_plot["Compliance"] = z_compliance
            if z_benign is not None and len(z_benign) > 0:
                data_to_plot["Benign"] = z_benign

        if len(data_to_plot) < 2:
            logging.warning(
                f"In the first{layer}layer ('{window_name}') There is insufficient data to generate the chart."
            )
            ax.text(
                0.5,
                0.5,
                f"Layer {layer}\nInsufficient Data",
                ha="center",
                va="center",
                fontsize=9,
            )
            ax.set_xticks([])
            ax.set_yticks([])
            continue

        min_samples = min(len(v) for v in data_to_plot.values())
        plot_sample_size = (
            min(sample_size, min_samples) if sample_size > 0 else min_samples
        )
        sampled_data = {
            k: v[torch.randperm(v.size(0))[:plot_sample_size]]
            for k, v in data_to_plot.items()
        }
        all_preprocessed = torch.cat(list(sampled_data.values()), dim=0)

        pca = PCA(n_components=2)
        pca.fit(all_preprocessed.numpy())

        proj_dfs = [
            pd.DataFrame(pca.transform(t.numpy()), columns=["PC1", "PC2"]).assign(
                Category=c
            )
            for c, t in sampled_data.items()
        ]
        proj_df = pd.concat(proj_dfs, ignore_index=True)

        current_plot_colors = {k: all_colors[k] for k in data_to_plot.keys()}
        sns.scatterplot(
            data=proj_df,
            x="PC1",
            y="PC2",
            hue="Category",
            palette=current_plot_colors,
            ax=ax,
            alpha=0.7,
            s=20,
        )
        ax.get_legend().remove()

        v_l = vectors[layer].get("v")
        c_l = vectors[layer].get("c")
        axis_width = ax.get_xlim()[1] - ax.get_xlim()[0]
        arrow_length = axis_width * 0.3

        if v_l is not None and torch.norm(v_l) > 0:
            proj_v = (v_l.numpy().reshape(1, -1)) @ pca.components_.T
            proj_v_norm = np.linalg.norm(proj_v)
            if proj_v_norm > 1e-9:
                scaled_proj_v = (proj_v / proj_v_norm) * arrow_length
                ax.quiver(
                    0,
                    0,
                    scaled_proj_v[0, 0],
                    scaled_proj_v[0, 1],
                    color=vec_colors["v_vector"],
                    scale=1,
                    scale_units="xy",
                    angles="xy",
                    width=0.01,
                    label=r"$v_l$",
                )
        if c_l is not None and torch.norm(c_l) > 0:
            proj_c = (c_l.numpy().reshape(1, -1)) @ pca.components_.T
            proj_c_norm = np.linalg.norm(proj_c)
            if proj_c_norm > 1e-9:
                scaled_proj_c = (proj_c / proj_c_norm) * arrow_length
                ax.quiver(
                    0,
                    0,
                    scaled_proj_c[0, 0],
                    scaled_proj_c[0, 1],
                    color=vec_colors["c_vector"],
                    scale=1,
                    scale_units="xy",
                    angles="xy",
                    width=0.01,
                    label=r"$c_l$",
                )

        ax.set_title(f"Layer {layer}")

    for j in range(i + 1, len(axes)):
        fig.delaxes(axes[j])

    first_valid_ax = next((ax for ax in axes if ax.has_data()), None)
    if first_valid_ax:
        handles, labels = first_valid_ax.get_legend_handles_labels()
        fig.legend(
            handles,
            labels,
            loc="lower center",
            ncol=len(handles),
            bbox_to_anchor=(0.5, 0.01),
        )

    title_prefix = "Whitened" if whitening_enabled else "Centered"
    fig.suptitle(
        f"PCA of {title_prefix} Activations ({window_name}) for {llm_name}", fontsize=16
    )
    plt.tight_layout(rect=[0, 0.05, 1, 0.96])

    output_path = output_dir / f"pca_visualization_{window_name}.png"
    plt.savefig(output_path, dpi=300)
    logging.info(f"PCA visualization plot saved to:{output_path}")
    plt.close(fig)


def find_subsequence(main_list: List[int], sub_list: List[int]) -> int:
    """Find the starting index of a sublist in the main list."""
    main_len = len(main_list)
    sub_len = len(sub_list)
    for i in range(main_len - sub_len + 1):
        if main_list[i : i + sub_len] == sub_list:
            return i
    return -1


def get_model_and_tokenizer(model_path: str, model_kwargs: dict, device: str):
    """Load the Hugging Face model and tokenizer."""
    logging.info(f"Loading model '{model_path}' Used for fraction calculations...")
    kwargs = model_kwargs.copy()
    if "torch_dtype" in kwargs and isinstance(kwargs["torch_dtype"], str):
        try:
            kwargs["torch_dtype"] = getattr(torch, kwargs["torch_dtype"])
        except AttributeError:
            if kwargs["torch_dtype"] != "auto":
                raise ValueError(f"Invalid torch_dtype:{kwargs['torch_dtype']}")

    model = AutoModelForCausalLM.from_pretrained(model_path, **kwargs).to(device)
    model.eval()
    tokenizer = AutoTokenizer.from_pretrained(
        model_path, trust_remote_code=True, padding_side="left"
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model.config.pad_token_id = tokenizer.pad_token_id
    logging.info("The model and tokenizer are loaded successfully.")
    return model, tokenizer


def calculate_and_save_token_scores(
    datasets_to_score: Dict[str, pd.DataFrame],
    model,
    tokenizer,
    transforms: Dict,
    condition_vectors: Dict,
    config: Dict,
    output_dir,
):
    """Efficiently reprocess samples, calculate and save token-by-token scores, no more using model.generate().
    This version uses a subsequence search to pinpoint the location of assistant_output.
    """
    llm_name = config["llm_name"]
    device = config["processing"]["device"]
    batch_size = config.get("processing", {}).get("batch_size", 4)

    layers = sorted(condition_vectors.keys())
    transforms_cont = transforms["content_window"]

    for name, df in datasets_to_score.items():
        if df is None or df.empty:
            logging.info(f"data set '{name}' is empty to skip fraction calculation.")
            continue

        logging.info(
            f"--- is working on '{name}' ({len(df)}samples) calculate token-by-token scores ---"
        )

        all_scores = {layer: [] for layer in layers}

        for i in tqdm(range(0, len(df), batch_size), desc=f"working on{name}score"):
            batch_df = df.iloc[i : i + batch_size]

            full_input_texts = []
            output_token_sequences = []

            for idx, row in batch_df.iterrows():
                prompt = str(row["prompt"]) if pd.notna(row["prompt"]) else ""
                assistant_output = (
                    str(row["assistant_output"])
                    if pd.notna(row["assistant_output"])
                    else ""
                )
                assistant_output = assistant_output.rstrip()

                # 1. Build a complete conversation history
                full_conversation = [
                    {"role": "user", "content": prompt},
                    {"role": "assistant", "content": assistant_output},
                ]
                full_text = apply_chat_template_compat(
                    tokenizer,
                    full_conversation, tokenize=False, add_generation_prompt=False
                )
                full_input_texts.append(full_text)

                # 2. Separately segment assistant_output for subsequent searches
                output_ids = tokenizer(
                    assistant_output, add_special_tokens=False
                ).input_ids
                output_token_sequences.append(output_ids)

                # 3. Batch segmentation of complete conversations
            inputs = tokenizer(
                full_input_texts, return_tensors="pt", padding=True, truncation=True
            ).to(device)

            # 4. Find the starting position of each assistant_output in the complete sequence
            output_start_indices = []
            for batch_idx in range(len(batch_df)):
                full_ids_list = inputs.input_ids[batch_idx].tolist()
                output_ids_list = output_token_sequences[batch_idx]

                start_idx = find_subsequence(full_ids_list, output_ids_list)
                output_start_indices.append(start_idx)

                # 5. Perform a forward pass
            with torch.no_grad():
                full_outputs = model(**inputs, output_hidden_states=True)
                all_hidden_states = full_outputs.hidden_states

                # 6. Calculate scores layer by layer and sample by sample
            for layer_idx in layers:
                if (
                    layer_idx not in transforms_cont
                    or layer_idx not in condition_vectors
                ):
                    continue

                layer_hidden_states = all_hidden_states[layer_idx].to(torch.float32)
                transform = transforms_cont[layer_idx]
                c_vector = condition_vectors[layer_idx].to(device, dtype=torch.float32)

                for batch_idx in range(len(batch_df)):
                    start_idx = output_start_indices[batch_idx]
                    output_len = len(output_token_sequences[batch_idx])

                    if start_idx == -1:
                        # If not found or the output is empty, the score is also empty
                        if output_len > 0:
                            logging.warning(
                                f"Unable to sample{df.index[i + batch_idx]}Locate the assistant_output token sequence."
                            )
                        scores = torch.tensor([], dtype=torch.float32)
                    else:
                        end_idx = start_idx + output_len
                        # The slicing operation automatically handles boundaries, no need for manual min
                        output_hidden_states = layer_hidden_states[
                            batch_idx, start_idx:end_idx, :
                        ]

                        if output_hidden_states.shape[0] > 0:
                            transformed_activations = apply_transform(
                                output_hidden_states, transform
                            )
                            scores = torch.einsum(
                                "sd,d->s", transformed_activations, c_vector
                            )
                        else:
                            scores = torch.tensor([], dtype=torch.float32)

                    all_scores[layer_idx].append(scores.cpu())

                    # 7. Clear memory
            del full_outputs, all_hidden_states, inputs
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            # 8. Save scores
        scores_save_path = output_dir / f"{llm_name}_{name}_token_scores.pt"
        torch.save(all_scores, scores_save_path)
        logging.info(
            f"Already '{name}''s token-by-token score is saved to{scores_save_path}"
        )


def main():
    parser = argparse.ArgumentParser(
        description="Extract intervention vectors and condition vectors from model activations."
    )
    parser.add_argument(
        "--config",
        type=str,
        default="../configs/extract_vectors_config.yaml",
        help="YAML configuration file path for vector extraction stage.",
    )
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.is_file():
        logging.error(f"Configuration file not found:{config_path}")
        return
    with open(config_path, "r", encoding="utf-8") as f:
        config = yaml.safe_load(f)

    base_dir = Path(__file__).parent.parent
    llm_name = config["llm_name"]
    data_dir = base_dir / config["data_dir"] / llm_name
    output_dir = base_dir / config["output_dir"] / llm_name
    output_dir.mkdir(parents=True, exist_ok=True)
    logging.info(f"All products will be saved to:{output_dir}")

    compliance_activations, compliance_df = load_and_filter_data(
        data_dir, llm_name, "compliance"
    )
    refusal_activations, refusal_df = load_and_filter_data(
        data_dir, llm_name, "refusal"
    )
    benign_activations, benign_df = load_and_filter_data(data_dir, llm_name, "benign")

    if not compliance_activations or not refusal_activations or not benign_activations:
        logging.error(
            "Required data set is missing and cannot continue. Please run the 02 and 02.5 scripts first."
        )
        return

    whitening_config = config.get("whitening", {})
    whitening_enabled = whitening_config.get("enabled", True)
    transforms_early, transforms_cont = calculate_dual_transforms(
        benign_activations, whitening_config
    )

    all_transforms = {
        "early_window": transforms_early,
        "content_window": transforms_cont,
    }
    torch.save(all_transforms, output_dir / "transforms.pt")
    logging.info(
        f"Transformation matrix (mean/whiten) saved to{output_dir / 'transforms.pt'}"
    )

    intervention_vectors, condition_vectors = {}, {}
    layers = sorted(list(benign_activations.keys()))

    preprocessed_activations_for_plot = {
        "early_window": {layer: {} for layer in layers},
        "content_window": {layer: {} for layer in layers},
    }
    all_vectors_for_plot = {layer: {} for layer in layers}

    log_balancing_info = True

    for layer in tqdm(layers, desc="Extract vector"):
        transform_early = transforms_early.get(layer)
        transform_cont = transforms_cont.get(layer)

        if not transform_early or not transform_cont:
            logging.warning(
                f"No.{layer}Layer is missing transformation matrix, vector extraction skipped."
            )
            continue

        H_refusal_early = refusal_activations.get(layer, {}).get("early_window")
        H_compliance_early = compliance_activations.get(layer, {}).get("early_window")
        H_benign_early = benign_activations.get(layer, {}).get("early_window")

        if (
            H_refusal_early is not None
            and H_compliance_early is not None
            and H_benign_early is not None
        ):
            z_refusal_early = apply_transform(
                H_refusal_early.cuda(), transform_early
            ).cpu()
            z_compliance_early = apply_transform(
                H_compliance_early.cuda(), transform_early
            ).cpu()
            z_benign_early = apply_transform(
                H_benign_early.cuda(), transform_early
            ).cpu()

            preprocessed_activations_for_plot["early_window"][layer][
                "refusal"
            ] = z_refusal_early
            preprocessed_activations_for_plot["early_window"][layer][
                "compliance"
            ] = z_compliance_early
            preprocessed_activations_for_plot["early_window"][layer][
                "benign"
            ] = z_benign_early

            if len(z_refusal_early) > 0 and len(z_compliance_early) > 0:
                n_refusal, n_compliance = len(z_refusal_early), len(z_compliance_early)
                min_samples_v = min(n_refusal, n_compliance)
                if log_balancing_info:
                    logging.info(
                        f"To extract a balanced sample of v_l: refusal({n_refusal}) vs compliance({n_compliance}). will use{min_samples_v}samples."
                    )
                indices_refusal = torch.randperm(n_refusal)[:min_samples_v]
                indices_compliance = torch.randperm(n_compliance)[:min_samples_v]

                # Modification: v_l (intervention vector) is no longer normalized
                v = get_diff_vector(
                    z_refusal_early[indices_refusal],
                    z_compliance_early[indices_compliance],
                )
                if (v @ z_refusal_early.mean(0)) <= (v @ z_compliance_early.mean(0)):
                    v = -v
                # v_norm = torch.norm(v) # <-- removed
                # intervention_vectors[layer] = v / v_norm if v_norm > 0 else v # <-- removed
                intervention_vectors[layer] = (
                    v  # <-- Directly save the vector with modulus length
                )

                all_vectors_for_plot[layer]["v"] = intervention_vectors[layer]

        H_compliance_cont = compliance_activations.get(layer, {}).get("content_window")
        H_benign_cont = benign_activations.get(layer, {}).get("content_window")
        H_refusal_cont = refusal_activations.get(layer, {}).get("content_window")

        if (
            H_compliance_cont is not None
            and H_benign_cont is not None
            and H_refusal_cont is not None
        ):
            z_compliance_cont = apply_transform(
                H_compliance_cont.cuda(), transform_cont
            ).cpu()
            z_benign_cont = apply_transform(H_benign_cont.cuda(), transform_cont).cpu()
            z_refusal_cont = apply_transform(
                H_refusal_cont.cuda(), transform_cont
            ).cpu()

            preprocessed_activations_for_plot["content_window"][layer][
                "compliance"
            ] = z_compliance_cont
            preprocessed_activations_for_plot["content_window"][layer][
                "benign"
            ] = z_benign_cont
            preprocessed_activations_for_plot["content_window"][layer][
                "refusal"
            ] = z_refusal_cont

            if len(z_compliance_cont) > 0 and len(z_benign_cont) > 0:
                n_compliance, n_benign = len(z_compliance_cont), len(z_benign_cont)
                min_samples_c = min(n_compliance, n_benign)
                if log_balancing_info:
                    logging.info(
                        f"To extract c_l balanced samples: compliance({n_compliance}) vs benign({n_benign}). will use{min_samples_c}samples."
                    )
                indices_compliance = torch.randperm(n_compliance)[:min_samples_c]
                indices_benign = torch.randperm(n_benign)[:min_samples_c]

                # Modification: c_l (condition vector) remains normalized
                c = get_diff_vector(
                    z_compliance_cont[indices_compliance], z_benign_cont[indices_benign]
                )
                if (c @ z_compliance_cont.mean(0)) <= (c @ z_benign_cont.mean(0)):
                    c = -c
                c_norm = torch.norm(c)
                condition_vectors[layer] = (
                    c / c_norm if c_norm > 0 else c
                )  # <-- keep normalized

                all_vectors_for_plot[layer]["c"] = condition_vectors[layer]

        if log_balancing_info:
            log_balancing_info = False

    if config.get("decoupling", {}).get("enabled", True):
        # Modification: Decoupling logic
        logging.info("Decoupling vectors (v_l only)...")
        for layer in layers:
            if layer in intervention_vectors and layer in condition_vectors:
                v_l, c_l = (
                    intervention_vectors[layer],
                    condition_vectors[layer],
                )  # v_l (band module length), c_l (unit vector)
                if torch.norm(v_l) > 0 and torch.norm(c_l) > 0:
                    # Only update v_l and remove the normalization of v_l
                    v_l_decoupled = v_l - (c_l @ v_l) * c_l
                    intervention_vectors[layer] = (
                        v_l_decoupled  # <-- direct assignment, retain the module length
                    )

                    # c_l will not be modified again
                    # c_l_decoupled = c_l - (v_l @ c_l) * v_l
                    # norm_c = torch.norm(c_l_decoupled)
                    # if norm_c > 0: condition_vectors[layer] = c_l_decoupled / norm_c

                all_vectors_for_plot[layer]["v"] = intervention_vectors[layer]
                all_vectors_for_plot[layer]["c"] = condition_vectors[
                    layer
                ]  # c_l remains unchanged

    torch.save(intervention_vectors, output_dir / "intervention_vectors.pt")
    logging.info(
        f"Intervention vector (v_l) [with modulus length] saved to{output_dir / 'intervention_vectors.pt'}"
    )
    torch.save(condition_vectors, output_dir / "condition_vectors.pt")
    logging.info(
        f"Condition vector (c_l) [normalized] saved to{output_dir / 'condition_vectors.pt'}"
    )

    vis_config = config.get("visualization", {})
    if vis_config.get("enabled", False):
        plot_pca_visualizations(
            llm_name=llm_name,
            window_name="early_window",
            layers=layers,
            activations=preprocessed_activations_for_plot["early_window"],
            vectors=all_vectors_for_plot,
            output_dir=output_dir,
            whitening_enabled=whitening_enabled,
            sample_size=vis_config.get("sample_size", 200),
        )
        plot_pca_visualizations(
            llm_name=llm_name,
            window_name="content_window",
            layers=layers,
            activations=preprocessed_activations_for_plot["content_window"],
            vectors=all_vectors_for_plot,
            output_dir=output_dir,
            whitening_enabled=whitening_enabled,
            sample_size=vis_config.get("sample_size", 200),
        )

    logging.info("The vector extraction process is completed.")

    # --- New: Calculate and save token-by-token scores ---
    logging.info("--- Start calculating token-by-token scores ---")

    # Check and set the configuration required for model loading
    if "model_path" not in config:
        config["model_path"] = f"../../../models/{config['llm_name']}"
        logging.warning(
            f"'model_path' not found in configuration. The inferred path is:{config['model_path']}"
        )
    if "model_kwargs" not in config:
        config["model_kwargs"] = {"torch_dtype": "bfloat16", "trust_remote_code": True}
        logging.warning("'model_kwargs' not found in configuration. Use default value.")

        # Load model
    model, tokenizer = get_model_and_tokenizer(
        config["model_path"],
        config["model_kwargs"],
        config.get("processing", {}).get("device", "cuda"),
    )

    datasets_to_score = {
        "compliance": compliance_df,
        "refusal": refusal_df,
        "benign": benign_df,
    }

    calculate_and_save_token_scores(
        datasets_to_score=datasets_to_score,
        model=model,
        tokenizer=tokenizer,
        transforms=all_transforms,
        condition_vectors=condition_vectors,
        config=config,
        output_dir=output_dir,
    )

    logging.info("All processes are completed.")


if __name__ == "__main__":
    main()
